"""uitgaven binnen een serie

Revision ID: 689efc4f2f93
Revises: 237bb71bd533
Create Date: 2026-08-12 13:56:43.671840

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '689efc4f2f93'
down_revision: str | Sequence[str] | None = '237bb71bd533'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edition_series_id'), ['series_id'], unique=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slot', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_book_edition_id'), ['edition_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_book_edition_id', 'edition', ['edition_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###

    _backfill()


def _backfill() -> None:
    """Wat er al staat een uitgave geven.

    Zonder dit hebben bestaande boeken geen uitgave, en dan valt er ook niets
    te ordenen. Twee soorten komen we tegen: bestanden op de NAS en delen van
    een abonnement. Een serie met beide krijgt ze allebei, met je eigen
    bestanden als eerste keus — die staan er tenslotte al.
    """
    bind = op.get_bind()

    for series_id, titel in bind.execute(sa.text("SELECT id, title FROM series")).fetchall():
        rang = 0

        lokaal = bind.execute(
            sa.text("SELECT COUNT(*) FROM book WHERE series_id = :s AND file_id IS NOT NULL"),
            {"s": series_id},
        ).scalar_one()
        if lokaal:
            edition_id = bind.execute(
                sa.text(
                    "INSERT INTO edition (series_id, name, rank, created_at) "
                    "VALUES (:s, 'Eigen bestanden', :r, CURRENT_TIMESTAMP) RETURNING id"
                ),
                {"s": series_id, "r": rang},
            ).scalar_one()
            bind.execute(
                sa.text(
                    "UPDATE book SET edition_id = :e "
                    "WHERE series_id = :s AND file_id IS NOT NULL"
                ),
                {"e": edition_id, "s": series_id},
            )
            rang += 1

        # Per abonnement één uitgave. Boeken zonder bestand horen bij de bron
        # waar ze vandaan komen; heeft een serie er maar één, dan is dat
        # eenduidig. Bij meerdere abonnementen op dezelfde bron valt het niet
        # meer af te leiden — dan komen ze bij de eerste terecht en verplaats
        # je ze zelf.
        abonnementen = bind.execute(
            sa.text(
                "SELECT sub.id, src.name FROM subscription sub "
                "JOIN source src ON src.id = sub.source_id "
                "WHERE sub.series_id = :s ORDER BY sub.id"
            ),
            {"s": series_id},
        ).fetchall()
        for index, (subscription_id, bron) in enumerate(abonnementen):
            edition_id = bind.execute(
                sa.text(
                    "INSERT INTO edition (series_id, name, rank, subscription_id, created_at) "
                    "VALUES (:s, :n, :r, :sub, CURRENT_TIMESTAMP) RETURNING id"
                ),
                {"s": series_id, "n": f"{titel} via {bron}", "r": rang, "sub": subscription_id},
            ).scalar_one()
            if index == 0:
                bind.execute(
                    sa.text(
                        "UPDATE book SET edition_id = :e "
                        "WHERE series_id = :s AND edition_id IS NULL"
                    ),
                    {"e": edition_id, "s": series_id},
                )
            rang += 1


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_edition_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_book_edition_id'))
        batch_op.drop_column('slot')
        batch_op.drop_column('edition_id')

    with op.batch_alter_table('edition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edition_series_id'))

    op.drop_table('edition')
    # ### end Alembic commands ###
