"""bron-reeks per abonnement

Revision ID: 6f74486915ef
Revises: 9c87d4d7df5c
Create Date: 2026-08-12 15:01:18.794728

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f74486915ef'
down_revision: str | Sequence[str] | None = '9c87d4d7df5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_ref', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###

    # Overnemen wat er al was: tot nu toe volgde elk abonnement de reeks van
    # zijn serie, want er kon er maar één zijn.
    op.execute(
        sa.text(
            "UPDATE subscription SET source_ref = ("
            "  SELECT source_ref FROM series WHERE series.id = subscription.series_id"
            ") WHERE source_ref IS NULL"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('source_ref')

    # ### end Alembic commands ###
