"""vastgezette hoofdstuktitels

Revision ID: 790ec65fa73e
Revises: 0ab7b09a33f0
Create Date: 2026-08-12 18:48:32.211949

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '790ec65fa73e'
down_revision: str | Sequence[str] | None = '0ab7b09a33f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        # server_default, anders weigert SQLite de kolom bij bestaande rijen.
        batch_op.add_column(
            sa.Column(
                'title_locked', sa.Boolean(), nullable=False, server_default=sa.text('0')
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('title_locked')

    # ### end Alembic commands ###
