"""initial schema

Revision ID: 9638a53a3591
Revises:
Create Date: 2026-08-10 20:11:46.565684

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9638a53a3591"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("smart", sa.Boolean(), nullable=False),
        sa.Column("rule", sa.JSON(), nullable=False),
        sa.Column("group_by", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "library_root",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("default_origin_language", sa.String(length=8), nullable=True),
        sa.Column(
            "default_origin_region",
            sa.Enum(
                "europe",
                "japan",
                "korea",
                "china",
                "us",
                "other",
                "unknown",
                name="origin_region",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("folder_as_collection", sa.Boolean(), nullable=False),
        sa.Column("last_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tab",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=60), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rule", sa.JSON(), nullable=False),
        sa.Column("view_mode", sa.String(length=20), nullable=False),
        sa.Column("group_by", sa.String(length=20), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tracker_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("credentials", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_root_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.Column("extension", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("missing", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["library_root_id"], ["library_root.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.create_index("ix_file_root_missing", ["library_root_id", "missing"], unique=False)

    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("library_root_id", sa.Integer(), nullable=True),
        sa.Column("folder_path", sa.String(length=1024), nullable=True),
        sa.Column("origin_language", sa.String(length=8), nullable=True),
        sa.Column("origin_country", sa.String(length=8), nullable=True),
        sa.Column(
            "origin_region",
            sa.Enum(
                "europe",
                "japan",
                "korea",
                "china",
                "us",
                "other",
                "unknown",
                name="origin_region",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin_source",
            sa.Enum(
                "manual",
                "online",
                "embedded",
                "root_default",
                "none",
                name="origin_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column("tracker_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["library_root_id"], ["library_root.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_root_id", "title", name="uq_series_root_title"),
    )
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_series_origin_region"), ["origin_region"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_series_sort_title"), ["sort_title"], unique=False)

    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("comic", "epub", "pdf", name="book_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=True),
        sa.Column("sort_number", sa.Float(), nullable=False),
        sa.Column("volume", sa.String(length=40), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("right_to_left", sa.Boolean(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id"),
    )
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_book_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_book_series_id"), ["series_id"], unique=False)
        batch_op.create_index("ix_book_series_sort", ["series_id", "sort_number"], unique=False)

    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column(
            "policy",
            sa.Enum("permanent", "readahead", name="subscription_policy", native_enum=False),
            nullable=False,
        ),
        sa.Column("readahead_n", sa.Integer(), nullable=False),
        sa.Column("ttl_days", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "download_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("pending", "running", "done", "failed", name="job_state", native_enum=False),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.JSON(), nullable=False),
        sa.Column("percent", sa.Float(), nullable=False),
        sa.Column("finished", sa.Boolean(), nullable=False),
        sa.Column("device", sa.String(length=100), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "book_id", name="uq_progress_user_book"),
    )
    op.create_table(
        "translation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("page_index", sa.Integer(), nullable=True),
        sa.Column("target_lang", sa.String(length=8), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "book_id", "page_index", "target_lang", "provider", name="uq_translation_target"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translation")
    op.drop_table("progress")
    op.drop_table("download_job")
    op.drop_table("subscription")
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.drop_index("ix_book_series_sort")
        batch_op.drop_index(batch_op.f("ix_book_series_id"))
        batch_op.drop_index(batch_op.f("ix_book_kind"))

    op.drop_table("book")
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_series_sort_title"))
        batch_op.drop_index(batch_op.f("ix_series_origin_region"))

    op.drop_table("series")
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index("ix_file_root_missing")

    op.drop_table("file")
    op.drop_table("user")
    op.drop_table("tracker_account")
    op.drop_table("tab")
    op.drop_table("source")
    op.drop_table("setting")
    op.drop_table("library_root")
    op.drop_table("collection")
    # ### end Alembic commands ###
