"""taal per abonnement

Revision ID: 9c87d4d7df5c
Revises: 689efc4f2f93
Create Date: 2026-08-12 14:40:34.068167

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9c87d4d7df5c'
down_revision: str | Sequence[str] | None = '689efc4f2f93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        # Met server_default, anders weigert SQLite de kolom bij bestaande
        # rijen: die zouden NULL krijgen in een NOT NULL-kolom. Wat er al stond
        # is Engels, want dat was tot nu toe de enige taal die opgehaald werd.
        batch_op.add_column(
            sa.Column('language', sa.String(length=8), nullable=False, server_default='en')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
